[theme]
base = "light"
primaryColor = "#2251FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F9"
textColor = "#051C2C"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
